import { GOODS, quote, marketStock, cargoUsed, cargoCapacity, CONTRACTS, dockedHarbor } from './commerce';
import { HARBORS, type Harbor, findHarbor } from './settlements';
import { UPGRADE_INFO, upgradeCost, upgradeProblem, type Progress, type Upgrade } from './progression';

export function equipmentPage(p: Progress) {
  const hub = dockedHarbor(p);
  return `<div class="workshop-notice">${hub?.workshop ? `At ${hub.name} · ready to install` : 'Equipment can only be installed after landing at a workshop. Look for the H landing symbol; press L on approach.'}</div><div class="wallet"><span>◇ ${p.parts} scrap</span><span>✧ ${p.cores} wind cores</span></div><div class="upgrade-grid">${(Object.keys(UPGRADE_INFO) as Upgrade[]).map(kind => {
    const info = UPGRADE_INFO[kind], cost = upgradeCost(p,kind), reason = upgradeProblem(p,kind), level = p.upgrades[kind];
    return `<article class="upgrade-card"><div class="upgrade-heading"><h3>${info.name}</h3><span>${'●'.repeat(level)}${'○'.repeat(3-level)}</span></div><p>${info.description}</p><small>${info.effect}</small><button data-upgrade="${kind}" ${reason ? 'disabled' : ''}>${level===3 ? 'Fully upgraded' : `${cost.parts} scrap${cost.cores ? ` + ${cost.cores} cores` : ''} · Install`}</button>${reason && level<3 ? `<span class="upgrade-reason">${reason}</span>` : ''}</article>`;
  }).join('')}</div><p class="journal-note">Advanced flight equipment needs regional schematics. Launchers, hulls and cargo cradles need scrap and cores. Loaded cargo increases sink and drag; leave some battery for the return trip.</p>`;
}
export function cargoPage(p: Progress) {
  const job = CONTRACTS.find(c=>c.id===p.freight), destination = job && findHarbor(job.to);
  return `<div class="cargo-summary"><strong>${cargoUsed(p)} / ${cargoCapacity(p)}</strong><span>cargo slots occupied<br>${p.deliveries.length} completed deliveries</span></div>${job ? `<article class="delivery-card"><span>${job.kind==='passenger' ? 'PASSENGER ABOARD' : 'FREIGHT ABOARD'}</span><h3>${job.name}</h3><p>${job.description}</p><p>Land at <b>${destination!.name}</b> to receive ${job.fee} scrap. Uses ${job.slots} slots.</p><button data-harbor-pin="${job.to}">Pin destination</button></article>` : '<p>Land at a flight house, market or depot to pick up a delivery or carry a paper traveler. One contract at a time; cargo space is shared with trade goods.</p>'}<div class="cargo-manifest">${Object.entries(GOODS).map(([id,g])=>`<span>${g.name}<b>${p.cargo[id as keyof typeof GOODS]}</b></span>`).join('')}</div><p class="journal-note">Buy local specialties and sell where they are needed. Tea is grown at Hearthside, paper is made at Willow Mill, copper comes from the mine and lens glass from Bellwether. Mountain settlements pay more for supplies. Cargo and contracts stay with you after a rescue.</p>`;
}
export function harborPage(p: Progress,h: Harbor,tab: string) {
  const active = CONTRACTS.find(c=>c.id===p.freight);
  let body = '';
  if (tab==='workshop') body=equipmentPage(p);
  else if (tab==='market') body=`<div class="market-heading"><span>LOCAL EXCHANGE</span><b>◇ ${p.parts} scrap · Cargo ${cargoUsed(p)}/${cargoCapacity(p)}</b></div><p class="journal-note">Prices are per crate. Stock is finite. Buying and selling here costs a spread; profit comes from carrying goods elsewhere.</p><div class="trade-list">${Object.entries(GOODS).map(([id,g])=>{
    const good=id as keyof typeof GOODS, price=quote(h.id,good), stock=marketStock(p,h.id,good);
    return `<article class="trade-row"><div><h3>${g.name}</h3><small>${stock} in stock · ${p.cargo[good]} aboard</small></div><button data-buy="${id}" ${!h.market || stock<=0 || p.parts<price.buy || cargoUsed(p)>=cargoCapacity(p) ? 'disabled' : ''}>Buy · ${price.buy}</button><button data-sell="${id}" ${!h.market || !p.cargo[good] ? 'disabled' : ''}>Sell · ${price.sell}</button></article>`;
  }).join('')}</div>`;
  else if (tab==='contracts') body=`${cargoPage(p)}<h3 class="harbor-subheading">On the departure board</h3>${CONTRACTS.filter(c=>c.from===h.id && !p.deliveries.includes(c.id)).map(c=>`<article class="delivery-card"><span>${c.kind==='passenger' ? 'PAPER TRAVELER' : 'SEALED FREIGHT'} · ${c.slots} SLOTS</span><h3>${c.name}</h3><p>${c.description}</p><small>To ${findHarbor(c.to)!.name} · ${c.fee} scrap on arrival</small><button data-contract="${c.id}" ${active || cargoUsed(p)+c.slots>cargoCapacity(p) || (c.requires && !p.defeated.includes(c.requires)) ? 'disabled' : ''}>${c.requires && !p.defeated.includes(c.requires) ? 'Defeat the Tempest Roc first' : active ? 'Finish your current delivery first' : cargoUsed(p)+c.slots>cargoCapacity(p) ? 'More cargo space needed' : 'Accept passage'}</button></article>`).join('') || '<p>No new departures here. Try another settlement’s board.</p>'}`;
  else body=`<div class="harbor-rest"><div class="harbor-seal">H</div><div><h3>Wings down. Take your time.</h3><p>${h.description}</p><span>Your glider is parked safely. Close this window to look around; L opens services again.</span></div></div><div class="service-grid"><button data-service="repair" ${!h.repair || p.health>=100 ? 'disabled' : ''}>Repair paper <small>${h.repair ? 'Complimentary · '+Math.ceil(p.health)+'% hull' : 'Unavailable here'}</small></button><button data-service="charge" ${!h.charge || !p.fan || p.charge>=100+p.upgrades.battery*60 ? 'disabled' : ''}>Charge fan <small>${!p.fan ? 'Discover a fan first' : h.charge ? 'Complimentary at this generator' : 'No generator at this stop'}</small></button><button data-service="ammo" ${p.parts<3 || p.ammo>87 ? 'disabled' : ''}>12 rubber bands <small>3 scrap · ${p.ammo} aboard</small></button></div>${active ? `<p class="journal-note">Aboard: ${active.name} → ${findHarbor(active.to)!.name}</p>` : ''}<p class="journal-note">Install equipment at workshops, trade specialties at markets, or pick up a delivery from the departure board.</p>`;
  return `<div class="eyebrow">WILLOWMERE FLIGHT HOUSES · SAFELY LANDED</div><h2 id="dialog-title">${h.name}</h2><div class="journal-tabs harbor-tabs"><button data-harbor-tab="rest" class="${tab==='rest'?'active':''}">Rest & service</button>${h.workshop ? `<button data-harbor-tab="workshop" class="${tab==='workshop'?'active':''}">Workshop</button>`:''}${h.market ? `<button data-harbor-tab="market" class="${tab==='market'?'active':''}">Market</button>`:''}<button id="harbor-atlas">Atlas map <small>J</small></button><button data-harbor-tab="contracts" class="${tab==='contracts'?'active':''}">Departures</button></div>${body}<div class="harbor-footer"><span>◇ ${p.parts} scrap · ✧ ${p.cores} cores</span><button id="depart-harbor">Take off →</button></div>`;
}
